name: CI PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Installer PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Installer les dépendances
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Lancer les tests
      run: vendor/bin/phpunit